/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gnQvwJ0C2tP
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function PricingPlans() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-6xl mx-auto">
      <Card className="bg-card text-card-foreground">
        <CardHeader className="border-b pb-6">
          <CardTitle className="text-2xl font-bold">Starter</CardTitle>
          <CardDescription className="text-muted-foreground">
            For individuals and small teams.
          </CardDescription>
        </CardHeader>
        <CardContent className="py-8 px-6 flex flex-col items-center gap-6">
          <div className="text-4xl font-bold">$9</div>
          <div className="text-muted-foreground text-sm">per month</div>
          <ul className="grid gap-2 text-sm">
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary" />5
              projects
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary" />
              10 GB storage
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary" />
              Basic support
            </li>
          </ul>
          <Button className="w-full">Get Started</Button>
        </CardContent>
      </Card>
      <Card className="bg-primary text-primary-foreground">
        <CardHeader className="border-b pb-6">
          <CardTitle className="text-2xl font-bold">Pro</CardTitle>
          <CardDescription className="text-primary-foreground">
            For growing teams and businesses.
          </CardDescription>
        </CardHeader>
        <CardContent className="py-8 px-6 flex flex-col items-center gap-6">
          <div className="text-4xl font-bold">$49</div>
          <div className="text-primary-foreground text-sm">per month</div>
          <ul className="grid gap-2 text-sm">
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary-foreground" />
              20 projects
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary-foreground" />
              100 GB storage
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary-foreground" />
              Priority support
            </li>
          </ul>
          <Button variant="secondary" className="w-full">
            Buy Now
          </Button>
        </CardContent>
      </Card>
      <Card className="bg-card text-card-foreground">
        <CardHeader className="border-b pb-6">
          <CardTitle className="text-2xl font-bold">Enterprise</CardTitle>
          <CardDescription className="text-muted-foreground">
            For large teams and organizations.
          </CardDescription>
        </CardHeader>
        <CardContent className="py-8 px-6 flex flex-col items-center gap-6">
          <div className="text-4xl font-bold">$499</div>
          <div className="text-muted-foreground text-sm">per month</div>
          <ul className="grid gap-2 text-sm">
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary" />
              Unlimited projects
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary" />1
              TB storage
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary" />
              Dedicated support
            </li>
          </ul>
          <Button className="w-full">Contact Sales</Button>
        </CardContent>
      </Card>
    </div>
  );
}

function CheckIcon(props: { className?: string }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}
